# Generated by Django 5.2.6 on 2025-11-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emociondetectada',
            name='emocion',
            field=models.CharField(max_length=50),
        ),
    ]
