# Generated by Django 5.2.6 on 2025-11-06 19:25

import Authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_alter_perfil_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, storage=Authentication.models.PerfilStorage(), upload_to=''),
        ),
    ]
